name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies for test Lambda
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Package Test Lambda Function
        run: zip -r test_function.zip .

      - name: Deploy to Test Lambda Function
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name sourcelambdatestcases \
            --zip-file fileb://test_function.zip \
            --region eu-north-1

      - name: Package Source Lambda Function
        run: zip -r source_function.zip index.js # Add any other necessary files

      - name: Deploy to Production Lambda
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name sourcelambda \
            --zip-file fileb://source_function.zip \
            --region eu-north-1 \
            --publish

      - name: Wait for Lambda update to complete
        run: sleep 10

      - name: Update Lambda Function Configuration
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-configuration \
            --function-name sourcelambda \
            --layers arn:aws:lambda:eu-north-1:022499012515:layer:sourceLambda:1 \
            --region eu-north-1
