name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install only dev dependencies (for testing purposes)
      - name: Install Jest (for testing)
        run: npm install --only=dev

      - name: Run Tests
        run: npm test

      - name: Package Lambda Function
        run: zip -r function.zip .

      - name: Deploy to Test Lambda Function
        if: success() # Only deploy if tests pass
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name sourcelambdatestcases \
            --zip-file fileb://function.zip \
            --region eu-north-1

      - name: Deploy to Production Lambda
        if: success() # Only deploy if tests and staging pass
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name sourcelambda \
            --zip-file fileb://function.zip \
            --region eu-north-1

      - name: Update Lambda Function Configuration
        if: success() # Only update configuration if deployment succeeds
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-configuration \
            --function-name sourcelambda \
            --layers arn:aws:lambda:eu-north-1:022499012515:layer:sourceLambda:1 \
            --region eu-north-1
